### ISSUE TITLE
Require new lines after multiline function signature

### ISSUE THREAD

**Issue by thaney071** [bombsimon/wsl#109]
The rule for a block should not start with a whitespace should not apply to a multiline function signature. Instead a no cuddle rule should be in place instead.

Example
```go
func (c *Client) GetSegment(
	ctx context.Context,
	uri *url.URL,
	out io.Writer,
) (written int64, err error) {

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, uri.String(), http.NoBody)
	if err != nil {
		return 0, errors.Wrap(err, "failed to create request for getting segment")
	}
...
}
```

**Comment by bombsimon** [comment]
I kept this issue open because I initially felt I wanted to support this. But now I'm a bit hesitant because removing this exact line was the core idea behind this linter. The reason I created it was because we weren't consistent at my workplace and I didn't want empty newlines. Back then we didn't use multi line function signatures so this wasn't a concern.

Since then I started to use multiline more but never really felt the need to add an empty line anyway. In fact when we get to multiline signatures, especially if the last argument is very long I often suggest a struct to use for call arguments.

Historically I've added configurable options before really thinking it through and I feel like adding too many options removes the positive side of having opinionated and less configurable formatters like `black`, `gofmt`, `rustfmt` and `gofumpt`. And speaking of `gofumpt`, that linter does not allow an empty line in this case and does not have an option to do so. I also found https://github.com/mvdan/gofumpt/issues/73 which has some examples and arguments regarding readability.

I'll most likely close this as wontfix but I'll hold of just a couple of more days if I find some reason to change my mind or get some other input.
