### ISSUE TITLE
Read closing bracket(s) as empty lines

### ISSUE THREAD

**Issue by jtagcat** [bombsimon/wsl#112]
I see this as just fine:
```go
	// ...
	}
}
return
```
```go
	// ...

	if err != nil
		return nil, err
	}
	return // "bad"
}
```

> return statements should not be cuddled if block has more than two lines

**Comment by bombsimon** [comment]
Both of these are valid:

```go
if err != nil {
    return 0, err
} else {
    return 1, nil
}
```

```go
if err != nil {
    return 0, err
}

return 1, nil
```

Just because something fits in an else block does not mean I want to reduce separation of control flow. The point of this rule is similar to the philosophy of `nlreturn` and for any non single line function `wsl` will require an empty line.

The ticket mentions to read _any_ bracket as an empty line even though the example is for error checking. I think that's also against the idea with `wsl` since that would allow something like this which is one of the most important rules in my opinion:

```go
if expr {
     //
}
if expr {
    //
}
```

I will close this as wontfix but feel free to add more context or thoughts if you think this would fit `wsl` or if I misinterpreted your thoughts here.

**Comment by jtagcat** [comment]
I disagree with my OP, you are right. Thanks
