### ISSUE TITLE
Issue with accessing functions and variables across files within the same package in v4

### ISSUE THREAD

**Issue by JuanJoseGonGi** [bombsimon/wsl#136]
I'm currently facing an issue while migrating from v3 to v4. In v3, I could run on a file that uses functions and variables from another file within the same package without any problems. However, in v4, this functionality seems to have changed. 

Here's an example of the issue:

v3:

```shell
wsl main.go && echo $status
0
```

To work around this problem in v4, I found that running all the *.go files seems to resolve the issue:

v4:
```shell
wsl main.go && echo $status
-: # command-line-arguments
./handler.go:4:11: undefined: x
path/to/main.go:4:11: undefined: x
wsl: 3 errors during loading
```

Workaround on v4:
```shell
wsl *.go && echo $status
0
```

I have created an [example repository](https://github.com/JuanJoseGonGi/wsl-error) to demonstrate this issue.

I would greatly appreciate any insights, suggestions, or potential solutions to overcome this problem in v4. Thank you in advance for your assistance!

Attached is a screenshot for reference:

<img width="1353" alt="Screenshot 2023-06-20 at 1 28 38 PM" src="https://github.com/bombsimon/wsl/assets/29153242/778c4dee-85e1-485c-9eb5-626250194c8a">

**Comment by bombsimon** [comment]
Hi! Thanks for the detailed ticket.

The reason for this is that v4 moved to using [analysis.Analyzer](https://pkg.go.dev/golang.org/x/tools/go/analysis#hdr-Analyzer) which was made to support auto fixes which was one of the most important things moving forward. The analyzer works on _package level_ which means it works the same way as the go compiler itself, this was added under the [usage](https://github.com/bombsimon/wsl#usage) section in the readme.

The reason `*.go` works is because it contains all the files included in the package. So to lint all files in one package you use `./path/to/package` and to lint all files in all packages you use `./...`.

To clarify, this is what the go compiler would do with your example:

```sh
› tail main.go another_file.go
==> main.go <==
package main

import "fmt"

func main() {
        fmt.Println(x)
}

==> another_file.go <==
package main

var x = 3
```

```sh
› go build main.go && echo $?
# command-line-arguments
./main.go:6:14: undefined: x
```

```sh
# Same as `go build *.go`
› go build ./ && echo $?
0
```

**Comment by JuanJoseGonGi** [comment]
Thank you for the detailed explanation. It clarifies the behavior in v4 and the usage of *.go as a workaround. Your response has been very helpful. Thank you once again for your assistance!
