### ISSUE TITLE
Allow cuddling of deferred statements referencing a pointer

### ISSUE THREAD

**Issue by forsak3n** [bombsimon/wsl#147]
Hi! Thanks for the linter, it's really great.

One thing that can be improved imo is cuddling of deferred statements. It's not uncommon to do something like this:

```golang
func doSomething() {
    labels := prometheus.Labels{
        "status": "published",
    }
    defer incrementCounter(&labels)

    if err := publish(); err != nil {
        labels["status"] = "dropped"
    }
}
```
Linter doesn't allow it though, and to me it would make sense to cuddle `labels` and deferred statement, because statement is referencing `labels`

**Comment by bombsimon** [comment]
Thanks for the report and sorry for a slow reply. This seems to be due to `allow-multi-line-assign` which I guess you've set to `false`? By default it's true and that would allow this:

```sh
› wsl .  # Ok
› wsl --allow-multi-line-assign=false .
/home/simon/tmp/x/main.go:9:2: defer statements should only be cuddled with expressions on same variable
```

This means that it will also work with bout if you do this (the assignment on a single line)

```go
labels := prometheus.Labels{"status": "published"}
defer incrementCounter(&labels)
```

```sh
› wsl .                                  # Ok
› wsl --allow-multi-line-assign=false .  # Ok
```

I think this is working as intended because setting `allow-multi-line-assign` to false is meant to treat assignments as isolated statements that should be separated.

**Comment by forsak3n** [comment]
@bombsimon that did the trick, thanks. Although, I'd prefer to keep multiline assignments set to false, it's a small sacrifice to make.
