### ISSUE TITLE
allow cuddling after instruction for return values

### ISSUE THREAD

**Issue by dionysius** [bombsimon/wsl#51]
I see this less often than my other issue and am also fine if this stays the same. But thought it is worth giving in my thoughts. The following issue has one popular case throughout my code in common, a function call expected to return a list. I'll try to elaborate.

If a function is expected to return a single element, but there is no such element, it usually returns an error indicating it is not found:
```golang
e, err := findElement()
if err != nil { // contains a `xyz not found` error
  return err
}
```

If a function is expected to return a list, but there are no elements matching, it doesn't return an error, since an empty list is expected. Only the caller knows if it wants tho have an empty result or not.
```golang
e, err := findElements()
if err != nil { // any lower level error, eg. timeout etc.
  return err
}
if len(e) == 0 { // cuddling allowance here for discussion
  return fmt.Errorf("not found")
}
```

But you can also have a function expecting to return nil even if no error happens:
```golang
e, err := findElement()
if err != nil { // any lower level error, eg. timeout etc
  return err
}
if e == nil { // cuddling allowance here for discussion
  return fmt.Errorf("...")
}
```

One could think, "yeah allow one cuddling once per return value, if the return value is used". If we think further, what do we do if we have many return values... that's gonna look awful probably.

I also have a small case - which looks like happening only once - is a needed type conversion after marshalling

```golang
yml, err := yaml.Marshal(s.NetworkConfig) // we can't convert types directly on multiple returns
if err != nil {
  return err
}
config[cfgNetwork] = string(yml) // config is map[string]string so it forced me to convert the type
```

And if we go further:
```golang
obj, err := someCall()
if err != nil {
  return err
}
if obj != nil {
  some.Foo = obj.r // to me this could be seen as a bad example, because I wouldn't allow cuddling for a usage of `obj` properties. (if you start to access properties, probably more assignments are here clogging the block)
  some.Foo = obj // instead this could be allowed
  return obj // or we could define strictly only allow if we use returns
}
```

**Comment by bombsimon** [comment]
Thanks for your view of this issue! For this issue I'm kind of sure that the linter is following my idea of style and readability. In my opinion the combination of `nil` and an error where `nil` is not a valid value is really unusual and kind of bad design. If you don't accept the nil value it should be reported in the error. One example of how to combine this would be the [sql](https://godoc.org/database/sql#pkg-variables) package where you would write something like this:

```go
result, err := sql.Exec(stmt)
if err != nil && err != sql.ErrNoRows {
    // This error is not because of an empty result, I wont accept it!
    return err
}

// Let's move on with empty resultset
```

You could also use else in your example:

```go
e, err := findElement()
if err != nil { // any lower level error, eg. timeout etc
  return err
} else if e == nil {
  return fmt.Errorf("...")
}
```

I would just use a blank line between the statements but if it's a common pattern I'll probably end up with something like this:

```go
e, err := mustFindOne(findElement())
if err != nil {
    return err
}

func mustFindOne(e []string, err) ([]string, err) {
    if len(e) == 0 {
        return e, errors.New("not found")
    }

    return e, err
}
```

Another reason why I don't think this is a good idea is because I think there are two separate things going on in the if statements. The `err != nil` is error checking and `len(e)` is business logic. I can only assume a 0 length response is valid since `err` is `nil`. I think those examples are applicable for the last example as well.

Regarding the casting I can somehow se that this is different although it also looks like an issue with the model. I would probably either change the type to `[]byte` or implement a wrapping method to convert it. I'm not saying it's applicable in your case (since you return `err`) but depending on your work flow this could be an alternative:

```go
if yml, err := yaml.Marshal(s.NetworkConfig); err == nil {
if err != nil {
    config[cfgNetwork] = string(yml)
}

// Move on
```

The last example could also be applicable in the last example since you're actually returning either `obj` or `err` so just invert the check to `if err == nil && obj != nil`.

So to sumarize, I think it's important to differentiate error checking and business logic. The `len` check is just one but imagine this:

```go
obj, err := GetObj()
if err != nil {
    return err
}
if obj.Foo == "" {
    return errors.New("foo empty")
}
if obj.Bar > 2 {
    return errors.New("bar to high")
}
if len(obj.Biz) != 3 {
    return errors.New("not 3 biz'es")
}
....
```

**Comment by dionysius** [comment]
> For this issue I'm kind of sure that the linter is following my idea of style and readability.

Thank you and I'm absolutely with you with that.

> I think it's important to differentiate error checking and business logic

That's the key point here. I was trying to hide the fact between error checking and business logic since the linter (I think) only operates on structure. It's also difficult to exclude personal bias, like putting assignments within an if state :)

> The len check is just one 

That's why I tried to explain only once per return value (which would include one for the error which would be compatible to the current implementation)

I also see no need for action here, just dumped my thoughts.

**Comment by bombsimon** [comment]
@dionysius Thank you again, keep posting issues with ideas and I'm glad to discuss them! I see you closed the issue but feel free to add new ones or keep them open, I don't mind. 😸 

I actually missed the details about max one cuddle check so thanks for pointing that out again however I feel like we're on the same page even with this issue closed!

**Comment by dionysius** [comment]
I just found a case similiar to type conversion: Having the need to assign pointers:

```golang
	mem, err := strconv.ParseInt(memStr, 10, 64)
	if err != nil {
		return nil, err
	}
	c.Resources.Memory.Limit = &mem
```

Again, like the yaml example, I only run in this case where I don't have control of the target type(s). `memStr` because of [lxd's config map](https://github.com/lxc/lxd/blob/bb5b28f346ffe94a02e53b0e9fe6634b9692a6a1/shared/api/container.go#L47) and pointer because of [opencontainers spec](https://github.com/opencontainers/runtime-spec/blob/19e92ca817772b4466f2ed2b8d808dfb7a8ab4be/specs-go/config.go#L281) and since theres no strconv.ParseIntPtr or so :)

No comments expected, just wanted to leave that here
