### ISSUE TITLE
var-- should count as assignment

### ISSUE THREAD

**Issue by troyronda** [bombsimon/wsl#57]
golangci-lint v1.21

```

rec.WaitCount--		 	
if rec.WaitCount == 0 {		 	
    return &delivering{}, nil		 			
}

```
resulted in a linter warning.

However an if statement following an assignment should be allowed.

**Comment by bombsimon** [comment]
@troyronda Thanks for the report!

This is fixed in `705d538` on master but not yet released in WSL or merged to golangci-lint!

I was hoping to get some work done with the fixer in #4 before the next PR to golangci-lint but I guess that might be a bit optimistic and since there are more fixes in wsl not yet merged to golangci-lint I might have to create a PR before the fixer is in place.

**Comment by bombsimon** [comment]
I've released [v1.2.6](https://github.com/bombsimon/wsl/releases/tag/v1.2.6) in WSL in the meantime so if it's really urgent it's possible to build golangci-lint from source.

**Comment by troyronda** [comment]
@bombsimon Excellent. Thanks for the update!

**Comment by bombsimon** [comment]
[PR](https://github.com/golangci/golangci-lint/pull/851) in `golangci-lint` to get this fix merged.

**Comment by bombsimon** [comment]
Merged to master i golangci-lint, closing
