### ISSUE TITLE
Message is unclear, perhaps wrong?

### ISSUE THREAD

**Issue by freman** [bombsimon/wsl#59]
So, getting block should not end with a whitespace (or comment)

```
logging/logcore.go:59:21: block should not end with a whitespace (or comment) (wsl)
                zapcore.FatalLevel:
```

```go
func (c *svcLoggingCore) Write(ent zapcore.Entry, fields []zapcore.Field) error {
	buf, err := c.enc.EncodeEntry(ent, fields)
	if err != nil {
		return err
	}

	switch ent.Level {
	case zapcore.InfoLevel:
		return c.logger.Info(buf.String())
	case zapcore.WarnLevel:
		return c.logger.Warning(buf.String())
	case zapcore.ErrorLevel,
		zapcore.DPanicLevel,
		zapcore.PanicLevel,
		zapcore.FatalLevel:
		return c.logger.Error(buf.String())
	}

	return nil
}
```

near as I can see gofmt made that code that format so, should be ok? or am I missing something

**Comment by bombsimon** [comment]
@freman Thanks for the report!

This seems to be from `golangci-lint` being behind latest release of `wsl`. `wsl` v1.2.7 got [merged yesterday](https://github.com/golangci/golangci-lint/pull/851) so now we'll have to wait for a new `golangci-lint` release.

If you build `golangci-lint` from master this issue disappears.

```sh
git clone https://github.com/golangci/golangci-lint
cd golangci-lint
go install ./...
```

Since I cannot do much more from this repository I'm closing this issue.
