### ISSUE TITLE
Is it possible to cuddled two related statements together with `if/for/switch`?

### ISSUE THREAD

**Issue by flw-cn** [bombsimon/wsl#71]
For example:

```Go
begin := getBegin()
end := getEnd()
if begin <= end {
    // do something
}
```

Now I have to add a blank line before `if`, otherwise I will get an error.

**Comment by bombsimon** [comment]
This is currently not allowed according to [this](https://github.com/bombsimon/wsl/blob/master/doc/rules.md#only-one-cuddle-assignment-allowed-before-if-statement) rule. It's been discussed before and the reason why it's not implemented is because if we allow two related statements, should we allow three? And if so, should we allow four? Five?

Consider this:

```go
one := getOne()
two := getTwo()
three := getThree()
four := getFour()
five := getFive()
if isTrue(one) && maybe(two).CanWorkWith(three) || four < valueOf(five) {
    // do something
}
```

They're all related but I don't think it's readable and I don't think it's something to encourage.

Regarding your example, I would do one of the following:

```go
begin := getBegin()
end := getEnd()

if begin <= end {
    // do something
}
```

```go
begin, end := getBegin(), getEnd()
if begin <= end {
    // do something
}
```

```go
begin, end := getBeginAndEnd()
if begin <= end {
    // do something
}
```

**Comment by dzpao** [comment]
You convinced me. indeed so. Although its intention is good, it is difficult to quantify.

**Comment by flw-cn** [comment]
You convinced me. indeed so. Although its intention is good, it is difficult to quantify.
