### ISSUE TITLE
Validate error if blocks 

### ISSUE THREAD

**Issue by artruora** [bombsimon/wsl#78]
Hi, I have the following issue while using the wsl tool

When two "if" blocks are together, I get: "if statements should only be cuddled with assignments"

```
func validateErr(err error) {
	if err == nil {
         ...
	}
	if errors.Is(err, ErrSomething) {
         ...
	}
...
}
```

But if I insert a space between them, i get : "if statements that check an error must be cuddled with the statement that assigned the error"

```
func validateErr(err error) {
	if err == nil {
         ...
	}

	if errors.Is(err, ErrSomething) {
         ...
	}
...
}
```

**Comment by bombsimon** [comment]
Thank your for the issue! That was interesting, haven't seen this yet but I guess it's kind of new since `errors.Is()` introduced.

So just to clarify, this only happens when `ForceCuddleErrCheckAndAssign` is set to true and `ErrorVariableNames` is set to `err` (this is default when using `-force-err-cuddling`).

I think I'll fix this by checking that if this is enabled, it will only trigger an error if the previous statement is an assign expression because it's only those we're looking to merge, assignments and checks.

**Comment by bombsimon** [comment]
This is now fixed and released under [v3.1.0](https://github.com/bombsimon/wsl/releases/tag/v3.1.0), please give it a try!

If you're using `golangci-lint` this change will not be reflected until an updated version is merged to master. In the meantime you can build your own version `golangci-lint` by cloning the repository and update the dependencies.

```sh
$ cd `golangci-lint`
$ go get -u github.com/bombsimon/wsl/v3@v3.1.0
$ go install ./...
```

**Comment by bombsimon** [comment]
Actually, I'll leave this open until it's merged to `golangci-lint` so I don't forget tis. :)

**Comment by bombsimon** [comment]
Merged in https://github.com/golangci/golangci-lint/pull/1750, will be available in next release.
